"""Async, fully-typed client library for the Ben Software SecuritySpy API.

The library owns all SecuritySpy protocol knowledge and imports nothing from
Home Assistant. It never creates an HTTP session: callers inject their own.
"""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _metadata_version

from .client import SecuritySpyClient
from .const import (
    BACKOFF_INITIAL,
    BACKOFF_JITTER,
    BACKOFF_MAX,
    BACKOFF_MULTIPLIER,
    CLASS_ANIMAL,
    CLASS_HUMAN,
    CLASS_VEHICLE,
    DEFAULT_PORT,
    DEFAULT_TIMEOUT,
    ENDPOINT_EVENT_STREAM,
    ENDPOINT_PREFIX,
    ENDPOINT_SYSTEM_INFO,
    EVENT_ARM_A,
    EVENT_ARM_C,
    EVENT_ARM_M,
    EVENT_CLASSIFY,
    EVENT_CONFIGCHANGE,
    EVENT_DISARM_A,
    EVENT_DISARM_C,
    EVENT_DISARM_M,
    EVENT_ERROR,
    EVENT_FILE,
    EVENT_MOTION,
    EVENT_MOTION_END,
    EVENT_NULL,
    EVENT_OFFLINE,
    EVENT_ONLINE,
    EVENT_STREAM_VERSION,
    EVENT_TRIGGER_A,
    EVENT_TRIGGER_M,
    HEARTBEAT_INTERVAL,
    HEARTBEAT_MISSES_BEFORE_LOSS,
    MIN_SERVER_VERSION,
    MIN_SERVER_VERSION_TEXT,
    PERM_AUDIORCV,
    PERM_AUDIOSND,
    PERM_CAMCONTROL,
    PERM_FILEDEL,
    PERM_FILES,
    PERM_LIVEVIDEO,
    PERM_PTZSET,
    PERM_SCHED,
    PERM_TRIGGER,
    PERMISSION_NAMES,
    STREAM_MAX_RECORD_BYTES,
    TRIGGER_REASON_NAMES,
    class_slug,
    decode_permissions,
    decode_trigger_reasons,
)
from .events import (
    ClassificationPayload,
    ErrorPayload,
    EventPayload,
    FilePayload,
    MotionPayload,
    StreamEvent,
    TriggerPayload,
    parse_event_line,
)
from .exceptions import (
    SecuritySpyAuthError,
    SecuritySpyConnectError,
    SecuritySpyError,
    SecuritySpyPermissionError,
    SecuritySpyUnsupportedVersionError,
)
from .models import Camera, ServerInfo
from .stream import EventCallback, LifecycleCallback, SecuritySpyEventStream

try:
    __version__ = _metadata_version("aiosecurityspy")
except PackageNotFoundError:  # pragma: no cover - source tree without install
    __version__ = "0.0.0.dev0"

__all__ = [
    "BACKOFF_INITIAL",
    "BACKOFF_JITTER",
    "BACKOFF_MAX",
    "BACKOFF_MULTIPLIER",
    "CLASS_ANIMAL",
    "CLASS_HUMAN",
    "CLASS_VEHICLE",
    "DEFAULT_PORT",
    "DEFAULT_TIMEOUT",
    "ENDPOINT_EVENT_STREAM",
    "ENDPOINT_PREFIX",
    "ENDPOINT_SYSTEM_INFO",
    "EVENT_ARM_A",
    "EVENT_ARM_C",
    "EVENT_ARM_M",
    "EVENT_CLASSIFY",
    "EVENT_CONFIGCHANGE",
    "EVENT_DISARM_A",
    "EVENT_DISARM_C",
    "EVENT_DISARM_M",
    "EVENT_ERROR",
    "EVENT_FILE",
    "EVENT_MOTION",
    "EVENT_MOTION_END",
    "EVENT_NULL",
    "EVENT_OFFLINE",
    "EVENT_ONLINE",
    "EVENT_STREAM_VERSION",
    "EVENT_TRIGGER_A",
    "EVENT_TRIGGER_M",
    "HEARTBEAT_INTERVAL",
    "HEARTBEAT_MISSES_BEFORE_LOSS",
    "MIN_SERVER_VERSION",
    "MIN_SERVER_VERSION_TEXT",
    "PERMISSION_NAMES",
    "PERM_AUDIORCV",
    "PERM_AUDIOSND",
    "PERM_CAMCONTROL",
    "PERM_FILEDEL",
    "PERM_FILES",
    "PERM_LIVEVIDEO",
    "PERM_PTZSET",
    "PERM_SCHED",
    "PERM_TRIGGER",
    "STREAM_MAX_RECORD_BYTES",
    "TRIGGER_REASON_NAMES",
    "Camera",
    "ClassificationPayload",
    "ErrorPayload",
    "EventCallback",
    "EventPayload",
    "FilePayload",
    "LifecycleCallback",
    "MotionPayload",
    "SecuritySpyAuthError",
    "SecuritySpyClient",
    "SecuritySpyConnectError",
    "SecuritySpyError",
    "SecuritySpyEventStream",
    "SecuritySpyPermissionError",
    "SecuritySpyUnsupportedVersionError",
    "ServerInfo",
    "StreamEvent",
    "TriggerPayload",
    "__version__",
    "class_slug",
    "decode_permissions",
    "decode_trigger_reasons",
    "parse_event_line",
]
